name: Tag and Publish

on:
  push:
    branches: [ main ]

jobs:
  tag-and-publish:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -e .
    
    - name: Get version
      id: get_version
      run: |
        $version = python -c "import openscope_experimental_launcher; print(openscope_experimental_launcher.__version__)"
        echo "version=$version" >> $env:GITHUB_OUTPUT
    
    - name: Check if tag exists
      id: check_tag
      run: |
        $tagExists = git tag -l "v${{ steps.get_version.outputs.version }}"
        if ($tagExists) {
          echo "exists=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "exists=false" >> $env:GITHUB_OUTPUT
        }
    
    - name: Create tag
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "v${{ steps.get_version.outputs.version }}"
        git push origin "v${{ steps.get_version.outputs.version }}"
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      if: steps.check_tag.outputs.exists == 'false'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
